# Generated by Django 3.1 on 2021-02-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_uploadimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isBlocked',
            field=models.BooleanField(default=False),
        ),
    ]
