# Generated by Django 3.1 on 2021-02-18 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_isblocked'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadImage',
        ),
    ]
