# Generated by Django 3.1 on 2021-02-21 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210220_2052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportedPost',
        ),
    ]
